[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "cd shared && npm install",
  "cd ../server && npm install"
]

[phases.build]
cmds = [
  "cd shared && npm run build",
  "cd ../server && npm run build"
]

[start]
cmd = "cd server && npm start"
