[build]
builder = "NIXPACKS"
buildCommand = "cd shared && npm install && npm run build && cd ../server && npm install && npm run build"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "ON_FAILURE"
